/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     GAP = 200
     CLOCK_FREQUENCY = 50000000/16
*/
module button_5 (
    input clk,
    input in,
    output reg out
  );
  
  localparam GAP = 8'hc8;
  localparam CLOCK_FREQUENCY = 26'h02faf08;
  
  
  reg [19:0] M_gap_counter_d, M_gap_counter_q = 1'h0;
  wire [1-1:0] M_buffer_out;
  reg [1-1:0] M_buffer_in;
  edge_detector_14 buffer (
    .clk(clk),
    .in(M_buffer_in),
    .out(M_buffer_out)
  );
  wire [1-1:0] M_rise_out;
  reg [1-1:0] M_rise_in;
  edge_detector_14 rise (
    .clk(clk),
    .in(M_rise_in),
    .out(M_rise_out)
  );
  
  always @* begin
    M_gap_counter_d = M_gap_counter_q;
    
    M_buffer_in = in;
    M_rise_in = 1'h0;
    if ((|M_gap_counter_q)) begin
      M_gap_counter_d = M_gap_counter_q - 1'h1;
    end else begin
      if (M_buffer_out) begin
        M_gap_counter_d = 34'h000098968;
        M_rise_in = 1'h1;
      end
    end
    out = M_rise_out;
  end
  
  always @(posedge clk) begin
    M_gap_counter_q <= M_gap_counter_d;
  end
  
endmodule
