/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module seven_segment_decoder_34 (
    input [3:0] value,
    output reg [6:0] segs
  );
  
  
  
  always @* begin
    
    case (value)
      1'h0: begin
        segs = 7'h7e;
      end
      1'h1: begin
        segs = 7'h48;
      end
      2'h2: begin
        segs = 7'h3d;
      end
      2'h3: begin
        segs = 7'h6d;
      end
      3'h4: begin
        segs = 7'h4b;
      end
      3'h5: begin
        segs = 7'h67;
      end
      3'h6: begin
        segs = 7'h77;
      end
      3'h7: begin
        segs = 7'h4c;
      end
      4'h8: begin
        segs = 7'h7f;
      end
      4'h9: begin
        segs = 7'h6f;
      end
      4'ha: begin
        segs = 7'h5b;
      end
      4'hb: begin
        segs = 7'h37;
      end
      4'hc: begin
        segs = 7'h32;
      end
      default: begin
        segs = 7'h00;
      end
    endcase
  end
endmodule
