/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     GAP = 500
     CLOCK_FREQUENCY = 50000000
*/
module button_4 (
    input clk,
    input in,
    output reg out
  );
  
  localparam GAP = 9'h1f4;
  localparam CLOCK_FREQUENCY = 26'h2faf080;
  
  
  reg [24:0] M_gap_counter_d, M_gap_counter_q = 1'h0;
  wire [1-1:0] M_buffer_out;
  reg [1-1:0] M_buffer_in;
  edge_detector_16 buffer (
    .clk(clk),
    .in(M_buffer_in),
    .out(M_buffer_out)
  );
  wire [1-1:0] M_rise_out;
  reg [1-1:0] M_rise_in;
  edge_detector_16 rise (
    .clk(clk),
    .in(M_rise_in),
    .out(M_rise_out)
  );
  
  always @* begin
    M_gap_counter_d = M_gap_counter_q;
    
    M_buffer_in = in;
    M_rise_in = 1'h0;
    if ((|M_gap_counter_q)) begin
      M_gap_counter_d = M_gap_counter_q - 1'h1;
    end else begin
      if (M_buffer_out) begin
        M_gap_counter_d = 35'h0017d7840;
        M_rise_in = 1'h1;
      end
    end
    out = M_rise_out;
  end
  
  always @(posedge clk) begin
    M_gap_counter_q <= M_gap_counter_d;
  end
  
endmodule
