/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module problems_2 (
    input [3:0] problem_count,
    output reg [9:0] problem_out
  );
  
  
  
  reg [99:0] p;
  
  always @* begin
    p = 100'hb5695ace34a02739ca5298251;
    problem_out = p[(problem_count)*10+9-:10];
  end
endmodule
