/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module randomGenerator_32 (
    input clk,
    input rst,
    output reg [3:0] out
  );
  
  
  
  reg [7:0] M_random_d, M_random_q = 1'h0;
  
  reg [3:0] rs;
  
  always @* begin
    M_random_d = M_random_q;
    
    M_random_d = M_random_q + 1'h1;
    rs = M_random_q - (M_random_q / 3'h4 * 3'h4);
    out = rs;
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_random_q <= 1'h0;
    end else begin
      M_random_q <= M_random_d;
    end
  end
  
endmodule
