/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     TIME = 200
*/
module beeper_2 (
    input clk,
    input rst,
    input in,
    input frequency,
    output reg wave
  );
  
  localparam TIME = 8'hc8;
  
  
  localparam TIMER_VALUE = 16'hc350;
  
  localparam FREQUENCY_COUNTER_VALUE = 25'h17d7840;
  
  wire [1-1:0] M_beep_cond_out;
  reg [1-1:0] M_beep_cond_in;
  edge_detector_14 beep_cond (
    .clk(clk),
    .in(M_beep_cond_in),
    .out(M_beep_cond_out)
  );
  reg [15:0] M_timer_d, M_timer_q = 1'h0;
  reg [15:0] M_frequency_counter_d, M_frequency_counter_q = 1'h0;
  reg [0:0] M_sound_d, M_sound_q = 1'h0;
  reg [0:0] M_voltage_d, M_voltage_q = 1'h0;
  
  always @* begin
    M_voltage_d = M_voltage_q;
    M_frequency_counter_d = M_frequency_counter_q;
    M_sound_d = M_sound_q;
    M_timer_d = M_timer_q;
    
    M_beep_cond_in = in;
    wave = M_voltage_q == 1'h1 && M_sound_q == 1'h1;
    if ((|M_timer_q)) begin
      M_timer_d = M_timer_q - 1'h1;
      M_sound_d = 1'h1;
    end else begin
      M_sound_d = 1'h0;
    end
    if (M_beep_cond_out) begin
      M_timer_d = 16'hc350;
    end
    M_frequency_counter_d = M_frequency_counter_q - 1'h1;
    if (M_frequency_counter_q == 1'h0) begin
      M_frequency_counter_d = 25'h17d7840 / frequency;
      M_voltage_d = ~M_voltage_q;
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_timer_q <= 1'h0;
      M_frequency_counter_q <= 1'h0;
      M_sound_q <= 1'h0;
      M_voltage_q <= 1'h0;
    end else begin
      M_timer_q <= M_timer_d;
      M_frequency_counter_q <= M_frequency_counter_d;
      M_sound_q <= M_sound_d;
      M_voltage_q <= M_voltage_d;
    end
  end
  
endmodule
